### ISSUE TITLE
Archive this repository

### ISSUE THREAD

**Issue by tobiasleibner** [dune-community/dune-xt-functions#100]
Before archiving, we should:
- Delete unused branches, for me everything expect the ``releases/*`` branches can be removed. Other opinions, @dune-community/dune-xt-devs?
- Update Readme to point to the new dune-xt repository

**Comment by ftalbrecht** [comment]
We should check which branches are referenced/used in publications, and keep those. Probably best if each of us lists the ones he still requires.

**Comment by renefritze** [comment]
What's the advantage of deleting branches before archiving?

**Comment by ftalbrecht** [comment]
On 23.03.20 17:19, René Fritze wrote:
> What's the advantage of deleting branches before archiving? 

Ah, right. Lets just keep everything and delte branches on the gitlab
side...

**Comment by renefritze** [comment]
That's what I was thinking, but unsure if I missed something.

**Comment by tobiasleibner** [comment]
When archiving, the repository becomes read-only, so these branches will stay here forever if i understand correctly. I thought it might be nice to cleanup the branches before. This way it is easier to see which branches contain useful code and maybe we also discover some branches that we might want to take over to dune-xt.

**Comment by renefritze** [comment]
I'd rather have the cleanup on the gitlab side since then we have a backup if remove too much and do not notice right away.

**Comment by tobiasleibner** [comment]
Okay, then the only thing left to do here is updating the Readme.

**Comment by renefritze** [comment]
@tobiasleibner has updated all the Readmes, thanks!
So now I'll go ahead and archive the repos.
