### ISSUE TITLE
extend bindings

### ISSUE THREAD

**Issue by ftalbrecht** [dune-community/dune-xt-functions#13]
See https://github.com/dune-community/dune-gdt/issues/95. We should not add grids here which are not present in dune-gdt.

**Comment by renefritze** [comment]
Note that dune-gdt is now restricted to one grid type. Switching it means recompile. Unless someone has an actual application with mixed grids currently I would be ok with doing the same thing in dune-xt modules.
The monolithic compile unit containing all bindings needs to be broken up btw. Other than that, extend for more functions, sure. @TiKeil is maybe on that atm.

**Comment by ftalbrecht** [comment]
> Unless someone has an actual application with mixed grids

In general, I think we would very much like to have that. In particular to have bindings ready for simplices and cubes and quickly prototype/test for a paper. But until we need this whatever currently works and is testet is fine for me.

>  I would be ok with doing the same thing in dune-xt modules

If stuff compiles in finite time for all grids I would like to keep that, if possible (see above).

> The monolithic compile unit containing all bindings needs to be broken up btw.

Here you mean dune-xt-grid and/or dune-xt-functions? Yes, this were the first bindings I wrote and they are really ugly... :/

**Comment by tobiasleibner** [comment]
Moved to dune-xt.
