### ISSUE TITLE
Replace random ellipsoids

### ISSUE THREAD

**Issue by renefritze** [dune-community/dune-xt-functions#17]
The current implementation isn't working well. I suggest replacing it with an ready made porous field generator from OpenPNM. This could also be an opportunity to look into python embedding via pybind11.

**Comment by renefritze** [comment]
We'll leave this open, but @TiKeil will go ahead and remove the current implementation before we have a replacement. Nobody's using it anyways.

**Comment by tobiasleibner** [comment]
Closing this for now, we can reopen this in dune-xt if we ever need it.
