### ISSUE TITLE
Parameterized function test is failing

### ISSUE THREAD

**Issue by renefritze** [dune-community/dune-xt-functions#18]
https://travis-ci.org/dune-community/dune-xt-functions/jobs/287487427#L3927

and fuller (local) log: https://pastebin.ca/3888217

Please have a look, @dune-community/dune-xt-functions-devs

**Comment by ftalbrecht** [comment]
Could be related to some changes in parameter parsing in dune-xt-common, which I introduced as a "fix" before my vacation. Will try to remember and investigate...

**Comment by ftalbrecht** [comment]
The fixes in common resolve the issue locally for me.
