### ISSUE TITLE
handle licensing of mathexpr

### ISSUE THREAD

**Issue by ftalbrecht** [dune-community/dune-xt-functions#2]
As far as I can see, the custom license in `mathexpr.{cc,hh}` is neither compatible with BSD-2 nor with any GPL, so we need to do something about that (at least mention this in `LICENSE`)...

**Comment by renefritze** [comment]
I'd say we check out http://warp.povusers.org/FunctionParser/ and get rid of that foobar parser.

**Comment by ftalbrecht** [comment]
Yes, we should get rid of that asap, but the license of the substitute
has to be appropriate...

**Comment by renefritze** [comment]
lgpl

**Comment by renefritze** [comment]
I'm listing some options I found browsing. None of those would be suitable to ship 'in-module', but rather via external-libraries:
- http://beltoforion.de/article.php?a=muparsersse
- https://github.com/ArashPartow/exprtk
- https://github.com/tartakynov/mathpresso

There's also https://github.com/arashpartow/math-parser-benchmark-project

Either way, finding a tiny library that's simultaneously BSD-2+lgpl compat seems not possible.

**Comment by tobiasleibner** [comment]
Moved to dune-xt.
