### ISSUE TITLE
Move xt-la from Suggests to Depends? (And other module deps)

### ISSUE THREAD

**Issue by renefritze** [dune-community/dune-xt-functions#24]
1. For some reason this popped up: https://travis-ci.org/dune-community/dune-xt-functions/jobs/344951460#L1227
So now I'm questioning whether we should just outright depend on xt-la. I see no reason other than being able to claim that the xt modules are more loosely coupled. Which I personally do not care about. 

2. In the same vein would be requiring istl for xt-la, where IMO gain very little by having it optional. OTOH we could lose a slew of ```#if HAVE_DUNE_ISTL``` and some builders on travis too. 

3. And while I'm at it: xt-grid currently suggests dune-fem and dune-pdelab. I see no reason for pdelab. Dune-fem is ofc still needed, but we could also drop the gridpart related abstractions now that dune-gdt does not need them any longer and then remove dune-fem from suggested modules in xt-grid. 

4. One more: xt-functions suggests dune-pdelab and dune-fem too. This I think we can drop right away, because xt-functions already depends on xt-grid, which (still) suggests those. 

5. xt-common only suggests dune-pybindxi. Requiring it would introduce a hard dependency on an available python3 interpreter. Which I am also perfectly fine with, since not one of the supercomputing platforms I currently use do not have at least a python 3.5 install. 

6. xt-common suggests dune-fem. This is due to being able to use that mpi and threading init stuff. This can be dropped if we drop dune-fem in 3.

This should probably all be decided and done during the-big-everything-change. Opinions, @dune-community/dune-xt-devs ?

**Comment by ftalbrecht** [comment]
> 1. For some reason this popped up: https://travis-ci.org/dune-community/dune-xt-functions/jobs/344951460#L1227
> So now I'm questioning whether we should just outright depend on xt-la. I see no reason other than being able to claim that the xt modules are more loosely coupled. Which I personally do not care about. 

I see no problem in dune-xt-functions depending on dune-xt-la.

> 2. In the same vein would be requiring istl for xt-la, where IMO gain very little by having it optional. OTOH we could lose a slew of ```#if HAVE_DUNE_ISTL``` and some builders on travis too. 

Agreed, dune-istl is easily available if you have access tot he other dune modules. No objections against letting dune-xt-la depending on dune-istl.

> 3. And while I'm at it: xt-grid currently suggests dune-fem and dune-pdelab. I see no reason for pdelab. Dune-fem is ofc still needed, but we could also drop the gridpart related abstractions now that dune-gdt does not need them any longer and then remove dune-fem from suggested modules in xt-grid.

Life would ne nicer without the view/part abstraction. Imho we could drop that (in particular everything `XT::Grid::Backend` related), but still keep the layer abstraction (until we have dynamic polymorphism for grid views). So no objection.

> 4. One more: xt-functions suggests dune-pdelab and dune-fem too. This I think we can drop right away, because xt-functions already depends on xt-grid, which (still) suggests those. 

I see no reason why dune-xt-function should depend or suggest either one.

> 5. xt-common only suggests dune-pybindxi. Requiring it would introduce a hard dependency on an available python3 interpreter. Which I am also perfectly fine with, since not one of the supercomputing platforms I currently use do not have at least a python 3.5 install. 

Here I am still a bit hesitant, but without strong objections.

> 6. xt-common suggests dune-fem. This is due to being able to use that mpi and threading init stuff. This can be dropped if we drop dune-fem in 3.

Agreed.

**Comment by renefritze** [comment]
On it.

**Comment by renefritze** [comment]
https://github.com/dune-community/dune-xt-super/pull/8
https://github.com/dune-community/dune-xt-la/pull/38
https://github.com/dune-community/dune-xt-common/pull/61
https://github.com/dune-community/dune-xt-grid/pull/46
https://github.com/dune-community/dune-xt-functions/pull/25

**Comment by renefritze** [comment]
I've changed everything accordingly. However for point 6. we should keep the the suggest line, unless we want to (somehow) prohibit dune-fem from being present. Even if we do not use anything from it in our own modules, if somewhere down the line someone does, we could break MPI init or some such, because without the Suggest dune-fem might get configured after dune-xt-common.

**Comment by ftalbrecht** [comment]
> I've changed everything accordingly.

thx

> However for point 6. we should keep the the suggest line, unless we want to (somehow) prohibit dune-fem from being present. Even if we do not use anything from it in our own modules, if somewhere down the line someone does, we could break MPI init or some such, because without the Suggest dune-fem might get configured after dune-xt-common.

Sounds reasonable, although I am not 100% sure. Since we will not use fem anywhere, our code and python bindings should be fine. The only thing that I could think of is having dune-fem present and dune-alugrid somehow doing strange stuff due to fems missing mpi init. I would be willing to test that, if we could afterwards drop it completely...

**Comment by renefritze** [comment]
Dune-alugrid uses no dune-fem code at all, AFAICT. The problem I'm seeing is rather that somewhere someone wants to use both dune-gdt and dune-fem in her module. Then that's going to be a problem if xt-common does not know that dune-fem will be used. That also affects Configuration and Threadmanager btw. All of which is super rarely touched code though and we gain little by removing it. Otoh, it will be effectively untested from now on. So, yeah, dunno actually what's best here.

**Comment by renefritze** [comment]
Dune-fem references are now gone from all xt-modules
