### ISSUE TITLE
Incorrect interface bindings

### ISSUE THREAD

**Issue by renefritze** [dune-community/dune-xt-functions#26]
I've had to disable some in https://github.com/dune-community/dune-xt-functions/pull/25/commits/2519275444cf37ae61e573547cbf4dff3bef7bb2
because those resulted in duplication of (at least) ```LocalizableFunctionInterface__1d_cube_yaspgrid_to_1x1```. 
I don't quite understand the current pattern of instantiations, but probably these should not be hardcoded, but rather generated depending on the grid type. 
Then again this will all change anyhow (rather soon?) so it might not be a priority to fix

**Comment by ftalbrecht** [comment]
Probably never compiled this for a 1d grid. Agreed regarding the latter.

**Comment by renefritze** [comment]
@TiKeil is prolly covering this currently

**Comment by renefritze** [comment]
Closing this myself since @TiKeil cannot.
