### ISSUE TITLE
introduce shape functions

### ISSUE THREAD

**Issue by ftalbrecht** [dune-community/dune-xt-functions#30]
Before merging #29, we should also

* intoduce `ShapeFunctionSet`, modelling a family of shape functions, which can be bound to a `GeometryType` (as opposed to a grid element), and thus to a reference element
* add a wrapper which takes a shape function set and derives from `LocalFunctionSet` (compare `as_localizable<E>()` of the `SmoothFunctionInterface`)
* add a way to obtain a shape function set corresponding to a subentity of a reference element (e.g., a reference intersection) given a shape function set corresponding to a reference element (e.g., the reference element of a grid element)
* rename `LocalFunctionSet` to `LocalElementFunctionSet`?, the latter is local in the sense of bound-to-the-reference-elemen-of-a-concrete-grid-element.
* add a `LocalIntersectionFunctionSet`, which can be bound to the intersection of a grid element
* add a way to obtain a `LocalIntersectionFunctionSet` from a `LocalElementFunctionSet`
* add a way to wrap a `ShapeFunctionSet` of dimension `d - 1` as a `LocalIntersectionFunctionSet` of the `d - 1`-dimensional intersection of a `d`-dimensional grid element

**Comment by ftalbrecht** [comment]
While all of the above would be nice, I think it should not be a show stopper for #29. We should rather do a release after #29 is merged and everything works and have the above as the roadmap for the next release.

**Comment by tobiasleibner** [comment]
Moved to dune-xt.
