### ISSUE TITLE
[functions] move to dune-gdt

### ISSUE THREAD

**Issue by renefritze** [dune-community/dune-xt-functions#4]
_From @ftalbrecht on February 6, 2015 11:4_

_Copied from original issue: wwu-numerik/dune-stuff#35_

**Comment by renefritze** [comment]
Is there a net benefit to this other than your feeling of them "belonging" there?

**Comment by renefritze** [comment]
_From @ftalbrecht on February 9, 2015 10:7_

Well, after the removal of the discrete function and dune-fem related stuff there is nothing left in dune stuff that makes use of those functions. With the EOL of dune-stuff possibly coming this year I am looking for where to place stuff. And since dune-gdt is the only place where those functions are used I thought to place them there. Another possible place would be the future `dune-grid-community`, but that does not exist yet...

**Comment by renefritze** [comment]
So wait and don't move twice?

**Comment by renefritze** [comment]
_From @ftalbrecht on February 10, 2015 12:21_

Sounds reasonable, yup.

**Comment by renefritze** [comment]
This can be closed now though, right @ftalbrecht ?

**Comment by ftalbrecht** [comment]
Ah, yes...
