### ISSUE TITLE
[flattop] implement localization

### ISSUE THREAD

**Issue by renefritze** [dune-community/dune-xt-functions#5]
_From @ftalbrecht on September 13, 2014 11:38_

`Functions::FlatTop` is derived from `GlobalFunctionInterface` which is problematic, since the order is globally specified. We need to implement a proper `local_function()` where the order is determined for each entity: If the entity lies
- completely wihtin or completely without the transition reagion we can return 0,
- complete within the transition region we can return `3*dimDomain`
- lies inbetween we should return something larger than `3*dimDomain`.

_Copied from original issue: wwu-numerik/dune-stuff#14_

**Comment by renefritze** [comment]
This can be closed, right @TiKeil @ftalbrecht ?

**Comment by ftalbrecht** [comment]
Well, the original issue remains. But I do not think it is pressing enough...
