### ISSUE TITLE
Do not download spe10 files on every cmake run

### ISSUE THREAD

**Issue by tobiasleibner** [dune-community/dune-xt-functions#55]
Currently, the spe10 model files are downloaded even if they are already existing.

**Comment by renefritze** [comment]
Uhm, didn't I replace those CMake downloads with using dxt-data already? Was this lost?

**Comment by tobiasleibner** [comment]
Oh, you are right. Probably that got lost when I merged master in new-master. I hope there's not too much else that got lost.
