### ISSUE TITLE
Reintroduce flux functions or something similar

### ISSUE THREAD

**Issue by tobiasleibner** [dune-community/dune-xt-functions#77]
Currently, we have ``Functions`` that only take source and range dimensions and can be evaluated in ("global") source coordinates, and ``GridFunctions`` that can be bound to an element and then evaluated in local coordinates. However, in hyperbolic equations we have a flux function that in general depends both on x (the grid coordinate) and u (a vector without corresponding grid). Currently, we can't model this function in dune-xt-functions. We used to have the ``FluxFunctionInterface`` that took two arguments in its evaluation, one in local grid coordinates and another grid-independent coordinate. We could just reintroduce this interface (updated to use ``bind``), or we can introduce something more general (arbitrary number of input variables? Could be hard to implement).

**Comment by TiKeil** [comment]
If I remember correctly, there was no particular reason for not adapting the flux functions to bind. I think we decided on whoever needs it is free to implement it.

**Comment by ftalbrecht** [comment]
No objections against resurrecting the fluxes from the graveyard. I am not quite certain what the interface would be like now that we have the local bindings of functions. Maybe we should discuss this in a pr in dune-xt-functions and a matching pr in dune-gdt, where we see how the existing numerical fluxes and local FV operators would need to be adapted?

**Comment by tobiasleibner** [comment]
Okay, I will prepare these PRs (will take a few days).

**Comment by tobiasleibner** [comment]
Done.
