### ISSUE TITLE
drop gcc-4.9 support?

### ISSUE THREAD

**Issue by ftalbrecht** [dune-community/dune-xt-functions#9]
`gcc` 4.9 does not play nicely with the python bindings, see https://travis-ci.org/dune-community/dune-xt-functions/jobs/170190102. Any objections against dropping support for `gcc` 4.9, @dune-community/dune-xt-common-devs?

**Comment by renefritze** [comment]
Would be good to know what the actual error is and why gcc 4.9 cannot work with the version of pybind 11. 
I'm against dropping gcc 4.9 without a good reason atm, because I need the 4.9 stdlib headers when compiling with ICC. If we drop support using gcc 4.9 as a compiler, this won't get tested.

**Comment by renefritze** [comment]
Also, isn't disabling Python bindings with 4.9 an option?

**Comment by ftalbrecht** [comment]
Agreed. Unfortunately I do not haave a gcc 4.9 lying around, so figuring aout the actual error will take me some time. Disabling bindings generation would probably be easier...

**Comment by ftalbrecht** [comment]
Not gonna happen. Gcc 4.9.4 is the minimal version we have to support for manylinux. The issue has been resolved by now...
